anchor:
  sizes: [3, 6, 9]
  ratios: [[1.0, 1.0], [1.0, 1.5], [1.5, 1.0]]

data:
  loader: 'voc'
  train_path: /dataset/voc_train
  test_path: /dataset/voc_test
  num_classes: 100

roi_size: 7
roi_overlap_threshold: 0.4
max_num_rois: 300


train:
  epoch: 200
  lr: 1e-5
  max_iou: 0.7
  min_iou: 0.3
  max_num_gt_boxes: 100
  batch_size: 2

  checkpoint_dir: _ckpt
  restore_ckpt: True
  model_file: model.h5
  load_saved_model: True
